version: "3"
services:
    server:
        image: ab-server-test
        build: .
        command: "node server.js"
        ports:
            - "4200:4200"
        depends_on:
            - "mongo"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    mongo:
        image: "mongo"
        ports:
            - "27017:27017"
